---
title: ""
author: "Greg"
date: ""
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UNC WBB/24-25 Games")
```

```{r, results='hide', include=FALSE,echo=FALSE}
select_opp <- 'Virginia'
opp_image <- 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Virginia_Cavaliers_logo.svg/1200px-Virginia_Cavaliers_logo.svg.png'
unc_image <- 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/North_Carolina_Tar_Heels_logo.svg/400px-North_Carolina_Tar_Heels_logo.svg.png'
```

```{r, results='hide', include=FALSE,echo=FALSE}
library(dplyr)
library(tidyr)
library(tidyverse)
library(gt)
library(gtExtras)
library(ggplot2)
library(devtools)
library(data.table)
library(cowplot)
library(gridExtra)
library(glue)
library(here)
library(magick)
library(scales)
library(readxl)
library(ggforce)
```

```{r, results='hide', include=FALSE,echo=FALSE}
header_df <- data.frame(one = opp_image,
                        two = paste0(select_opp, ' vs. North Carolina<br>March 2, 2024'),
                        three = unc_image)
header_tbl <- header_df %>%
  gt() %>%
  tab_options(column_labels.hidden = TRUE) %>%
  text_transform(locations = cells_body(vars(one)), fn = function(x) {web_image(url = x, height = px(80))}) %>%
  text_transform(locations = cells_body(vars(three)), fn = function(x) {web_image(url = x, height = px(80))}) %>%
  fmt_markdown(columns = vars(two)) %>%
  tab_options(table.background.color = 'white') %>%
  tab_style(style = list(cell_text(align = "center")), locations = cells_body()) %>%
  tab_style(style = list(cell_text(weight = "bold", color = "black", size = px(28))), locations = cells_body(vars(two))) %>%
  cols_width(one ~ px(175), two ~ px(550), three ~ px(175))
header_tbl

first_half_df <- data.frame(one = '1st Half')
first_half_tbl <- first_half_df %>%
  gt() %>%
  tab_options(column_labels.hidden = TRUE) %>%
  tab_options(table.background.color = 'white') %>%
  tab_style(style = list(cell_text(align = "center")), locations = cells_body()) %>%
  tab_style(style = list(cell_text(weight = "bold", color = "black", size = px(22), decorate = 'underline')), locations = cells_body(vars(one))) %>%
  cols_width(one ~ px(120))
first_half_tbl

second_half_df <- data.frame(one = '2nd Half')
second_half_tbl <- second_half_df %>%
  gt() %>%
  tab_options(column_labels.hidden = TRUE) %>%
  tab_options(table.background.color = 'white') %>%
  tab_style(style = list(cell_text(align = "center")), locations = cells_body()) %>%
  tab_style(style = list(cell_text(weight = "bold", color = "black", size = px(22), decorate = 'underline')), locations = cells_body(vars(one))) %>%
  cols_width(one ~ px(120))
second_half_tbl

full_df <- data.frame(one = 'Full Game')
full_tbl <- full_df %>%
  gt() %>%
  tab_options(column_labels.hidden = TRUE) %>%
  tab_options(table.background.color = 'white') %>%
  tab_style(style = list(cell_text(align = "center")), locations = cells_body()) %>%
  tab_style(style = list(cell_text(weight = "bold", color = "black", size = px(22), decorate = 'underline')), locations = cells_body(vars(one))) %>%
  cols_width(one ~ px(120))
full_tbl
```

```{r, results='hide', include=FALSE,echo=FALSE}
path <- '/Users/gregorylederer/Desktop/UNC WBB/24-25 Games/S&D_Tracker.xlsx'
data <- read_excel(path)
opp_row <- data[16,]
data <- data[-c(15:16),]
unc_deflections <- sum(data$Deflections)
unc_steals <- sum(data$Steals)

text <- data.frame(one = paste0(select_opp, ' - ', opp_row$Deflections[1], ' Deflections & ', opp_row$Steals[1], ' Steals | North Carolina - ', unc_deflections, ' Deflections & ', unc_steals, ' Steals'))
sd_tbl <- text %>%
  gt() %>%
  tab_options(column_labels.hidden = TRUE) %>%
  tab_options(table.background.color = 'white') %>%
  tab_style(style = list(cell_text(align = "center")), locations = cells_body()) %>%
  tab_style(style = list(cell_text(weight = "bold", color = "black", size = px(18))), locations = cells_body(vars(one))) %>%
  cols_width(one ~ px(900))
sd_tbl
```

```{r, results='hide', include=FALSE,echo=FALSE}
path <- '/Users/gregorylederer/Desktop/UNC WBB/24-25 Games/Game | ShotCharts.xltm'
colnames <- c('Day', 'Opp', 'Half', 'Rim_Make', 'Rim_Miss', 'Paint_Make', 'Paint_Miss', 'MidLC_Make', 'MidLC_Miss', 'MidLW_Make', 'MidLW_Miss', 'MidRW_Make', 'MidRW_Miss', 'MidRC_Make', 'MidRC_Miss', 'ThreeLC_Make', 'ThreeLC_Miss', 'ThreeLW_Make', 'ThreeLW_Miss', 'ThreeTop_Make', 'ThreeTop_Miss', 'ThreeRW_Make', 'ThreeRW_Miss', 'ThreeRC_Make', 'ThreeRC_Miss')
sheet_names <- excel_sheets(path)[-1]
shotchart_data_list <- lapply(sheet_names, function(sheet) {
  data <- read_excel(path, sheet = sheet)
  data <- data[-1, ]
  colnames(data) <- colnames
  data <- data %>%
    mutate(across(4:25, as.numeric))
  return(data)
})
names(shotchart_data_list) <- sheet_names
combined_data <- lapply(shotchart_data_list, function(data) {
  data %>%
    filter(Opp == select_opp & Half == 'First')
}) %>%
  bind_rows()
combined_df <- combined_data %>%
  summarize(across(4:25, sum, na.rm = TRUE)) %>%
  mutate(Day = NA, Opp = NA, Half = NA)
combined_df <- combined_df %>%
  mutate(
    Rim = paste0(Rim_Make, '/', Rim_Make+Rim_Miss),
    Rim. = round((Rim_Make/(Rim_Make+Rim_Miss))*100,1),
    Paint = paste0(Paint_Make, '/', Paint_Make+Paint_Miss),
    Paint. = round((Paint_Make/(Paint_Make+Paint_Miss))*100,1),
    MidLC = paste0(MidLC_Make, '/', MidLC_Make+MidLC_Miss),
    MidLC. = round((MidLC_Make/(MidLC_Make+MidLC_Miss))*100,1),
    MidLW = paste0(MidLW_Make, '/', MidLW_Make+MidLW_Miss),
    MidLW. = round((MidLW_Make/(MidLW_Make+MidLW_Miss))*100,1),
    MidRW = paste0(MidRW_Make, '/', MidRW_Make+MidRW_Miss),
    MidRW. = round((MidRW_Make/(MidRW_Make+MidRW_Miss))*100,1),
    MidRC = paste0(MidRC_Make, '/', MidRC_Make+MidRC_Miss),
    MidRC. = round((MidRC_Make/(MidRC_Make+MidRC_Miss))*100,1),
    ThreeLC = paste0(ThreeLC_Make, '/', ThreeLC_Make+ThreeLC_Miss),
    ThreeLC. = round((ThreeLC_Make/(ThreeLC_Make+ThreeLC_Miss))*100,1),
    ThreeLW = paste0(ThreeLW_Make, '/', ThreeLW_Make+ThreeLW_Miss),
    ThreeLW. = round((ThreeLW_Make/(ThreeLW_Make+ThreeLW_Miss))*100,1),
    ThreeTop = paste0(ThreeTop_Make, '/', ThreeTop_Make+ThreeTop_Miss),
    ThreeTop. = round((ThreeTop_Make/(ThreeTop_Make+ThreeTop_Miss))*100,1),
    ThreeRW = paste0(ThreeRW_Make, '/', ThreeRW_Make+ThreeRW_Miss),
    ThreeRW. = round((ThreeRW_Make/(ThreeRW_Make+ThreeRW_Miss))*100,1),
    ThreeRC = paste0(ThreeRC_Make, '/', ThreeRC_Make+ThreeRC_Miss),
    ThreeRC. = round((ThreeRC_Make/(ThreeRC_Make+ThreeRC_Miss))*100,1),
  )
combined_df[is.na(combined_df)] = 0
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4", '#7bafd4'),
    domain = c(0, 50, 100),
    na.color = "white"
  )(values)
}
combined_df <- combined_df %>%
  mutate(
    Rim_pred = custom_color_scale(Rim.),
    Paint_pred = custom_color_scale(Paint.),
    MidLC_pred = custom_color_scale(MidLC.),
    MidLW_pred = custom_color_scale(MidLW.),
    MidRW_pred = custom_color_scale(MidRW.),
    MidRC_pred = custom_color_scale(MidRC.),
    ThreeLC_pred = custom_color_scale(ThreeLC.),
    ThreeLW_pred = custom_color_scale(ThreeLW.),
    ThreeTop_pred = custom_color_scale(ThreeTop.),
    ThreeRW_pred = custom_color_scale(ThreeRW.),
    ThreeRC_pred = custom_color_scale(ThreeRC.)
  )
first_court <- ggplot() +
  # Outline court
  geom_rect(aes(ymin = 0, ymax = -19, xmin = -8, xmax = -8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = -19, ymax = -19, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = 0, ymax = -19, xmin = 8, xmax = 8), color = 'black', fill = NA) +
  # paint color
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = combined_df$Paint_pred, color = NA, alpha = 0.5) +
  # rim color
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = combined_df$Rim_pred, color = NA, alpha = 1) +
  # mid left corner color
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidLC_pred, alpha = 0.5) +
  # mid right corner color
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidRC_pred, alpha = 0.5) +
  # mid left wing color
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  # mid right wing color
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  # three left corner color
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeLC_pred, alpha = 0.5) +
  # three right corner color
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeRC_pred, alpha = 0.5) +
  # three left wing color
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeLW_pred, alpha = 0.5) +
  # three right wing color
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeRW_pred, alpha = 0.5) +
  # three top key color
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = combined_df$ThreeTop_pred, alpha = 0.5) +
  # rim text
  geom_text(aes(x = 0, y = -5), label = combined_df$Rim, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -7), label = paste0(combined_df$Rim., "%"), size = 5, color = "black", fontface = "bold") +
  # paint text
  geom_text(aes(x = 0, y = -15), label = combined_df$Paint, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -17), label = paste0(combined_df$Paint., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left corner text
  geom_text(aes(x = -16.5, y = -5), label = combined_df$MidLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -7), label = paste0(combined_df$MidLC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right corner text
  geom_text(aes(x = 16.5, y = -5), label = combined_df$MidRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -7), label = paste0(combined_df$MidRC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left wing text
  geom_text(aes(x = -13, y = -17), label = combined_df$MidLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -19), label = paste0(combined_df$MidLW., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right wing text
  geom_text(aes(x = 13, y = -17), label = combined_df$MidRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -19), label = paste0(combined_df$MidRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three left corner text
  geom_text(aes(x = -33, y = -4), label = combined_df$ThreeLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -6), label = paste0(combined_df$ThreeLC., "%"), size = 5, color = "black", fontface = "bold") +
  # three right corner text
  geom_text(aes(x = 33, y = -4), label = combined_df$ThreeRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -6), label = paste0(combined_df$ThreeRC., "%"), size = 5, color = "black", fontface = "bold") +
  # three left wing text
  geom_text(aes(x = -23, y = -23), label = combined_df$ThreeLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -25), label = paste0(combined_df$ThreeLW., "%"), size = 5, color = "black", fontface = "bold") +
  # three right wing text
  geom_text(aes(x = 23, y = -23), label = combined_df$ThreeRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -25), label = paste0(combined_df$ThreeRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three top key text
  geom_text(aes(x = 0, y = -30), label = combined_df$ThreeTop, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -32), label = paste0(combined_df$ThreeTop., "%"), size = 5, color = "black", fontface = "bold") +
  # Backboard
  geom_segment(aes(y = -2, x = -3, yend = -2, xend = 3), color = "black") +
  # Hoop
  geom_circle(aes(y0 = -2.8, x0 = 0, r = 0.75), color = "black", fill = NA) +
  # Three-point line (arc)
  geom_arc(aes(y0 = 0, x0 = 0, r = 27, start = ((pi/2)+0.3), end = (((3*pi)/2)-0.3)), color = "black") +
  # Three-point line (sides)
  geom_segment(aes(y = 0, x = 25.76, yend = -8, xend = 25.76), color = "black") +
  geom_segment(aes(y = 0, x = -25.76, yend = -8, xend = -25.76), color = "black") +
  # Sidelines
  geom_segment(aes(y = 0, x = -30, yend = 0, xend = 30), color = "black") +
  geom_segment(aes(y = -40, x = -30, yend = -40, xend = 30), color = "black") +
  geom_segment(aes(y = 0, x = -30, yend = -40, xend = -30), color = "black") +
  geom_segment(aes(y = 0, x = 30, yend = -40, xend = 30), color = "black") +
  # Dotted rim circle
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), color = "black", fill = NA, linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  
  coord_fixed() +
  theme_void() 
  #only 1H
  #theme(panel.background = element_rect(fill = "white")) +
  #geom_text(aes(x = -23, y = -38), label = "Shooting %", size = 5, color = "black", fontface = "bold")
first_court

att_rate_df <- combined_df %>%
  mutate(
    Rim_ar = round(((Rim_Make+Rim_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    Paint_ar = round(((Paint_Make+Paint_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidLC_ar = round(((MidLC_Make+MidLC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidLW_ar = round(((MidLW_Make+MidLW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidRW_ar = round(((MidRW_Make+MidRW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidRC_ar = round(((MidRC_Make+MidRC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeLC_ar = round(((ThreeLC_Make+ThreeLC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeLW_ar = round(((ThreeLW_Make+ThreeLW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeTop_ar = round(((ThreeTop_Make+ThreeTop_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeRW_ar = round(((ThreeRW_Make+ThreeRW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeRC_ar = round(((ThreeRC_Make+ThreeRC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1)
  ) %>%
  select(Rim_ar, Paint_ar, MidLC_ar, MidLW_ar, MidRW_ar, MidRC_ar, ThreeLC_ar, ThreeLW_ar, ThreeTop_ar, ThreeRW_ar, ThreeRC_ar)
min_attempt_rate <- min(att_rate_df, na.rm = TRUE)
max_attempt_rate <- max(att_rate_df, na.rm = TRUE)
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4"),
    domain = c(min_attempt_rate, max_attempt_rate),
    na.color = "white"
  )(values)
}
att_rate_df <- att_rate_df %>%
  mutate(
    Rim_color = custom_color_scale(Rim_ar),
    Paint_color = custom_color_scale(Paint_ar),
    MidLC_color = custom_color_scale(MidLC_ar),
    MidLW_color = custom_color_scale(MidLW_ar),
    MidRW_color = custom_color_scale(MidRW_ar),
    MidRC_color = custom_color_scale(MidRC_ar),
    ThreeLC_color = custom_color_scale(ThreeLC_ar),
    ThreeLW_color = custom_color_scale(ThreeLW_ar),
    ThreeTop_color = custom_color_scale(ThreeTop_ar),
    ThreeRW_color = custom_color_scale(ThreeRW_ar),
    ThreeRC_color = custom_color_scale(ThreeRC_ar)
  )
first_court_ar <- ggplot() +
  # Court background color zones for each attempt rate
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = att_rate_df$Paint_color, color = NA, alpha = 0.5) +  # Paint area
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = att_rate_df$Rim_color, color = NA, alpha = 1) +  # Rim area
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = att_rate_df$MidLC_color, alpha = 0.5) +  # Mid Left Corner
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = att_rate_df$MidRC_color, alpha = 0.5) +  # Mid Right Corner
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = att_rate_df$MidLW_color, alpha = 0.5) +  # Mid Left Wing
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = att_rate_df$MidLW_color, alpha = 0.5) +
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = att_rate_df$MidRW_color, alpha = 0.5) +  # Mid Right Wing
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = att_rate_df$MidRW_color, alpha = 0.5) +
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = att_rate_df$ThreeLC_color, alpha = 0.5) +  # Three Left Corner
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = att_rate_df$ThreeRC_color, alpha = 0.5) +  # Three Right Corner
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = att_rate_df$ThreeLW_color, alpha = 0.5) +  # Three Left Wing
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = att_rate_df$ThreeRW_color, alpha = 0.5) +  # Three Right Wing
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = att_rate_df$ThreeTop_color, alpha = 0.5) +  # Three Top Key
  
  # Attempt rate text for each zone
  geom_text(aes(x = 0, y = -5), label = paste0(att_rate_df$Rim_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -15), label = paste0(att_rate_df$Paint_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -5), label = paste0(att_rate_df$MidLC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -5), label = paste0(att_rate_df$MidRC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -17), label = paste0(att_rate_df$MidLW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -17), label = paste0(att_rate_df$MidRW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -4), label = paste0(att_rate_df$ThreeLC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -4), label = paste0(att_rate_df$ThreeRC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -23), label = paste0(att_rate_df$ThreeLW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -23), label = paste0(att_rate_df$ThreeRW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -30), label = paste0(att_rate_df$ThreeTop_ar), size = 5, color = "black", fontface = "bold") +
  
  # Court lines and details
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_segment(aes(x = -3, y = -2, xend = 3, yend = -2), color = "black") +  # Backboard
  geom_circle(aes(x0 = 0, y0 = -2.8, r = 0.75), color = "black", fill = NA) +  # Hoop
  geom_circle(aes(x0 = 0, y0 = -4.5, r = 4.5), color = "black", linetype = "dotted") +  # Dotted rim circle
  geom_arc(aes(x0 = 0, y0 = 0, r = 27, start = pi/2 + 0.3, end = 3 * pi / 2 - 0.3), color = "black") +  # 3-point arc
  geom_segment(aes(x = 25.76, y = -8, xend = 25.76, yend = 0), color = "black") +  # Right 3-point line
  geom_segment(aes(x = -25.76, y = -8, xend = -25.76, yend = 0), color = "black") +  # Left 3-point line
  geom_segment(aes(x = -30, y = -40, xend = 30, yend = -40), color = "black") +  # Baseline
  geom_segment(aes(x = -30, y = 0, xend = 30, yend = 0), color = "black") +  # Top sideline
  geom_segment(aes(x = -30, y = 0, xend = -30, yend = -40), color = "black") +  # Left sideline
  geom_segment(aes(x = 30, y = 0, xend = 30, yend = -40), color = "black") +  # Right sideline
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  #only for 2H
  labs(title = "Attempt Rates", subtitle = "Per 100 FGA") +
  
  coord_fixed() +
  theme_void() + # Remove background and grid lines
  #only for 2H
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold"), plot.subtitle = element_text(size = 12, hjust = 0.5))
  #only for 1H
  #theme(panel.background = element_rect(fill = "white")) +
  #geom_text(aes(x = -22, y = -38), label = "Attempt Rates", size = 5, color = "black", fontface = "bold")
first_court_ar

#only 1H
# savename1 <- paste0('1H ', select_opp, ' | Shot Chart.png')
# savename2 <- paste0('1H ', select_opp, ' | Att Shot Chart.png')
# ggsave(plot = first_court, filename = savename1)
# ggsave(plot = first_court_ar, filename = savename2)
```


```{r, results='hide', include=FALSE,echo=FALSE}
path <- '/Users/gregorylederer/Desktop/UNC WBB/24-25 Games/Game | ShotCharts.xltm'
colnames <- c('Day', 'Opp', 'Half', 'Rim_Make', 'Rim_Miss', 'Paint_Make', 'Paint_Miss', 'MidLC_Make', 'MidLC_Miss', 'MidLW_Make', 'MidLW_Miss', 'MidRW_Make', 'MidRW_Miss', 'MidRC_Make', 'MidRC_Miss', 'ThreeLC_Make', 'ThreeLC_Miss', 'ThreeLW_Make', 'ThreeLW_Miss', 'ThreeTop_Make', 'ThreeTop_Miss', 'ThreeRW_Make', 'ThreeRW_Miss', 'ThreeRC_Make', 'ThreeRC_Miss')
sheet_names <- excel_sheets(path)[-1]
shotchart_data_list <- lapply(sheet_names, function(sheet) {
  data <- read_excel(path, sheet = sheet)
  data <- data[-1, ]
  colnames(data) <- colnames
  data <- data %>%
    mutate(across(4:25, as.numeric))
  return(data)
})
names(shotchart_data_list) <- sheet_names
combined_data <- lapply(shotchart_data_list, function(data) {
  data %>%
    filter(Opp == select_opp & Half == 'Second')
}) %>%
  bind_rows()
combined_df <- combined_data %>%
  summarize(across(4:25, sum, na.rm = TRUE)) %>%
  mutate(Day = NA, Opp = NA, Half = NA)
combined_df <- combined_df %>%
  mutate(
    Rim = paste0(Rim_Make, '/', Rim_Make+Rim_Miss),
    Rim. = round((Rim_Make/(Rim_Make+Rim_Miss))*100,1),
    Paint = paste0(Paint_Make, '/', Paint_Make+Paint_Miss),
    Paint. = round((Paint_Make/(Paint_Make+Paint_Miss))*100,1),
    MidLC = paste0(MidLC_Make, '/', MidLC_Make+MidLC_Miss),
    MidLC. = round((MidLC_Make/(MidLC_Make+MidLC_Miss))*100,1),
    MidLW = paste0(MidLW_Make, '/', MidLW_Make+MidLW_Miss),
    MidLW. = round((MidLW_Make/(MidLW_Make+MidLW_Miss))*100,1),
    MidRW = paste0(MidRW_Make, '/', MidRW_Make+MidRW_Miss),
    MidRW. = round((MidRW_Make/(MidRW_Make+MidRW_Miss))*100,1),
    MidRC = paste0(MidRC_Make, '/', MidRC_Make+MidRC_Miss),
    MidRC. = round((MidRC_Make/(MidRC_Make+MidRC_Miss))*100,1),
    ThreeLC = paste0(ThreeLC_Make, '/', ThreeLC_Make+ThreeLC_Miss),
    ThreeLC. = round((ThreeLC_Make/(ThreeLC_Make+ThreeLC_Miss))*100,1),
    ThreeLW = paste0(ThreeLW_Make, '/', ThreeLW_Make+ThreeLW_Miss),
    ThreeLW. = round((ThreeLW_Make/(ThreeLW_Make+ThreeLW_Miss))*100,1),
    ThreeTop = paste0(ThreeTop_Make, '/', ThreeTop_Make+ThreeTop_Miss),
    ThreeTop. = round((ThreeTop_Make/(ThreeTop_Make+ThreeTop_Miss))*100,1),
    ThreeRW = paste0(ThreeRW_Make, '/', ThreeRW_Make+ThreeRW_Miss),
    ThreeRW. = round((ThreeRW_Make/(ThreeRW_Make+ThreeRW_Miss))*100,1),
    ThreeRC = paste0(ThreeRC_Make, '/', ThreeRC_Make+ThreeRC_Miss),
    ThreeRC. = round((ThreeRC_Make/(ThreeRC_Make+ThreeRC_Miss))*100,1),
  )
combined_df[is.na(combined_df)] = 0
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4", '#7bafd4'),
    domain = c(0, 50, 100),
    na.color = "white"
  )(values)
}
combined_df <- combined_df %>%
  mutate(
    Rim_pred = custom_color_scale(Rim.),
    Paint_pred = custom_color_scale(Paint.),
    MidLC_pred = custom_color_scale(MidLC.),
    MidLW_pred = custom_color_scale(MidLW.),
    MidRW_pred = custom_color_scale(MidRW.),
    MidRC_pred = custom_color_scale(MidRC.),
    ThreeLC_pred = custom_color_scale(ThreeLC.),
    ThreeLW_pred = custom_color_scale(ThreeLW.),
    ThreeTop_pred = custom_color_scale(ThreeTop.),
    ThreeRW_pred = custom_color_scale(ThreeRW.),
    ThreeRC_pred = custom_color_scale(ThreeRC.)
  )
second_court <- ggplot() +
  # Outline court
  geom_rect(aes(ymin = 0, ymax = -19, xmin = -8, xmax = -8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = -19, ymax = -19, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = 0, ymax = -19, xmin = 8, xmax = 8), color = 'black', fill = NA) +
  # paint color
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = combined_df$Paint_pred, color = NA, alpha = 0.5) +
  # rim color
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = combined_df$Rim_pred, color = NA, alpha = 1) +
  # mid left corner color
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidLC_pred, alpha = 0.5) +
  # mid right corner color
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidRC_pred, alpha = 0.5) +
  # mid left wing color
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  # mid right wing color
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  # three left corner color
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeLC_pred, alpha = 0.5) +
  # three right corner color
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeRC_pred, alpha = 0.5) +
  # three left wing color
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeLW_pred, alpha = 0.5) +
  # three right wing color
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeRW_pred, alpha = 0.5) +
  # three top key color
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = combined_df$ThreeTop_pred, alpha = 0.5) +
  # rim text
  geom_text(aes(x = 0, y = -5), label = combined_df$Rim, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -7), label = paste0(combined_df$Rim., "%"), size = 5, color = "black", fontface = "bold") +
  # paint text
  geom_text(aes(x = 0, y = -15), label = combined_df$Paint, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -17), label = paste0(combined_df$Paint., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left corner text
  geom_text(aes(x = -16.5, y = -5), label = combined_df$MidLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -7), label = paste0(combined_df$MidLC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right corner text
  geom_text(aes(x = 16.5, y = -5), label = combined_df$MidRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -7), label = paste0(combined_df$MidRC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left wing text
  geom_text(aes(x = -13, y = -17), label = combined_df$MidLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -19), label = paste0(combined_df$MidLW., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right wing text
  geom_text(aes(x = 13, y = -17), label = combined_df$MidRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -19), label = paste0(combined_df$MidRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three left corner text
  geom_text(aes(x = -33, y = -4), label = combined_df$ThreeLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -6), label = paste0(combined_df$ThreeLC., "%"), size = 5, color = "black", fontface = "bold") +
  # three right corner text
  geom_text(aes(x = 33, y = -4), label = combined_df$ThreeRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -6), label = paste0(combined_df$ThreeRC., "%"), size = 5, color = "black", fontface = "bold") +
  # three left wing text
  geom_text(aes(x = -23, y = -23), label = combined_df$ThreeLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -25), label = paste0(combined_df$ThreeLW., "%"), size = 5, color = "black", fontface = "bold") +
  # three right wing text
  geom_text(aes(x = 23, y = -23), label = combined_df$ThreeRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -25), label = paste0(combined_df$ThreeRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three top key text
  geom_text(aes(x = 0, y = -30), label = combined_df$ThreeTop, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -32), label = paste0(combined_df$ThreeTop., "%"), size = 5, color = "black", fontface = "bold") +
  # Backboard
  geom_segment(aes(y = -2, x = -3, yend = -2, xend = 3), color = "black") +
  # Hoop
  geom_circle(aes(y0 = -2.8, x0 = 0, r = 0.75), color = "black", fill = NA) +
  # Three-point line (arc)
  geom_arc(aes(y0 = 0, x0 = 0, r = 27, start = ((pi/2)+0.3), end = (((3*pi)/2)-0.3)), color = "black") +
  # Three-point line (sides)
  geom_segment(aes(y = 0, x = 25.76, yend = -8, xend = 25.76), color = "black") +
  geom_segment(aes(y = 0, x = -25.76, yend = -8, xend = -25.76), color = "black") +
  # Sidelines
  geom_segment(aes(y = 0, x = -30, yend = 0, xend = 30), color = "black") +
  geom_segment(aes(y = -40, x = -30, yend = -40, xend = 30), color = "black") +
  geom_segment(aes(y = 0, x = -30, yend = -40, xend = -30), color = "black") +
  geom_segment(aes(y = 0, x = 30, yend = -40, xend = 30), color = "black") +
  # Dotted rim circle
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), color = "black", fill = NA, linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  
  coord_fixed() +
  theme_void()
second_court

att_rate_df <- combined_df %>%
  mutate(
    Rim_ar = round(((Rim_Make+Rim_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    Paint_ar = round(((Paint_Make+Paint_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidLC_ar = round(((MidLC_Make+MidLC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidLW_ar = round(((MidLW_Make+MidLW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidRW_ar = round(((MidRW_Make+MidRW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidRC_ar = round(((MidRC_Make+MidRC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeLC_ar = round(((ThreeLC_Make+ThreeLC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeLW_ar = round(((ThreeLW_Make+ThreeLW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeTop_ar = round(((ThreeTop_Make+ThreeTop_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeRW_ar = round(((ThreeRW_Make+ThreeRW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeRC_ar = round(((ThreeRC_Make+ThreeRC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1)
  ) %>%
  select(Rim_ar, Paint_ar, MidLC_ar, MidLW_ar, MidRW_ar, MidRC_ar, ThreeLC_ar, ThreeLW_ar, ThreeTop_ar, ThreeRW_ar, ThreeRC_ar)
min_attempt_rate <- min(att_rate_df, na.rm = TRUE)
max_attempt_rate <- max(att_rate_df, na.rm = TRUE)
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4"),
    domain = c(min_attempt_rate, max_attempt_rate),
    na.color = "white"
  )(values)
}
att_rate_df <- att_rate_df %>%
  mutate(
    Rim_color = custom_color_scale(Rim_ar),
    Paint_color = custom_color_scale(Paint_ar),
    MidLC_color = custom_color_scale(MidLC_ar),
    MidLW_color = custom_color_scale(MidLW_ar),
    MidRW_color = custom_color_scale(MidRW_ar),
    MidRC_color = custom_color_scale(MidRC_ar),
    ThreeLC_color = custom_color_scale(ThreeLC_ar),
    ThreeLW_color = custom_color_scale(ThreeLW_ar),
    ThreeTop_color = custom_color_scale(ThreeTop_ar),
    ThreeRW_color = custom_color_scale(ThreeRW_ar),
    ThreeRC_color = custom_color_scale(ThreeRC_ar)
  )
second_court_ar <- ggplot() +
  # Court background color zones for each attempt rate
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = att_rate_df$Paint_color, color = NA, alpha = 0.5) +  # Paint area
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = att_rate_df$Rim_color, color = NA, alpha = 1) +  # Rim area
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = att_rate_df$MidLC_color, alpha = 0.5) +  # Mid Left Corner
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = att_rate_df$MidRC_color, alpha = 0.5) +  # Mid Right Corner
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = att_rate_df$MidLW_color, alpha = 0.5) +  # Mid Left Wing
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = att_rate_df$MidLW_color, alpha = 0.5) +
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = att_rate_df$MidRW_color, alpha = 0.5) +  # Mid Right Wing
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = att_rate_df$MidRW_color, alpha = 0.5) +
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = att_rate_df$ThreeLC_color, alpha = 0.5) +  # Three Left Corner
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = att_rate_df$ThreeRC_color, alpha = 0.5) +  # Three Right Corner
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = att_rate_df$ThreeLW_color, alpha = 0.5) +  # Three Left Wing
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = att_rate_df$ThreeRW_color, alpha = 0.5) +  # Three Right Wing
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = att_rate_df$ThreeTop_color, alpha = 0.5) +  # Three Top Key
  
  # Attempt rate text for each zone
  geom_text(aes(x = 0, y = -5), label = paste0(att_rate_df$Rim_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -15), label = paste0(att_rate_df$Paint_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -5), label = paste0(att_rate_df$MidLC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -5), label = paste0(att_rate_df$MidRC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -17), label = paste0(att_rate_df$MidLW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -17), label = paste0(att_rate_df$MidRW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -4), label = paste0(att_rate_df$ThreeLC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -4), label = paste0(att_rate_df$ThreeRC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -23), label = paste0(att_rate_df$ThreeLW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -23), label = paste0(att_rate_df$ThreeRW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -30), label = paste0(att_rate_df$ThreeTop_ar), size = 5, color = "black", fontface = "bold") +
  
  # Court lines and details
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_segment(aes(x = -3, y = -2, xend = 3, yend = -2), color = "black") +  # Backboard
  geom_circle(aes(x0 = 0, y0 = -2.8, r = 0.75), color = "black", fill = NA) +  # Hoop
  geom_circle(aes(x0 = 0, y0 = -4.5, r = 4.5), color = "black", linetype = "dotted") +  # Dotted rim circle
  geom_arc(aes(x0 = 0, y0 = 0, r = 27, start = pi/2 + 0.3, end = 3 * pi / 2 - 0.3), color = "black") +  # 3-point arc
  geom_segment(aes(x = 25.76, y = -8, xend = 25.76, yend = 0), color = "black") +  # Right 3-point line
  geom_segment(aes(x = -25.76, y = -8, xend = -25.76, yend = 0), color = "black") +  # Left 3-point line
  geom_segment(aes(x = -30, y = -40, xend = 30, yend = -40), color = "black") +  # Baseline
  geom_segment(aes(x = -30, y = 0, xend = 30, yend = 0), color = "black") +  # Top sideline
  geom_segment(aes(x = -30, y = 0, xend = -30, yend = -40), color = "black") +  # Left sideline
  geom_segment(aes(x = 30, y = 0, xend = 30, yend = -40), color = "black") +  # Right sideline
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  
  labs(title = "Attempt Rates", subtitle = "Per 100 FGA") +
  
  coord_fixed() +
  theme_void() + # Remove background and grid lines
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold"), plot.subtitle = element_text(size = 12, hjust = 0.5))
second_court_ar
```

```{r, results='hide', include=FALSE,echo=FALSE}
path <- '/Users/gregorylederer/Desktop/UNC WBB/24-25 Games/Game | ShotCharts.xltm'
colnames <- c('Day', 'Opp', 'Half', 'Rim_Make', 'Rim_Miss', 'Paint_Make', 'Paint_Miss', 'MidLC_Make', 'MidLC_Miss', 'MidLW_Make', 'MidLW_Miss', 'MidRW_Make', 'MidRW_Miss', 'MidRC_Make', 'MidRC_Miss', 'ThreeLC_Make', 'ThreeLC_Miss', 'ThreeLW_Make', 'ThreeLW_Miss', 'ThreeTop_Make', 'ThreeTop_Miss', 'ThreeRW_Make', 'ThreeRW_Miss', 'ThreeRC_Make', 'ThreeRC_Miss')
sheet_names <- excel_sheets(path)[-1]
shotchart_data_list <- lapply(sheet_names, function(sheet) {
  data <- read_excel(path, sheet = sheet)
  data <- data[-1, ]
  colnames(data) <- colnames
  data <- data %>%
    mutate(across(4:25, as.numeric))
  return(data)
})
names(shotchart_data_list) <- sheet_names
combined_data <- lapply(shotchart_data_list, function(data) {
  data %>%
    filter(Opp == select_opp)
}) %>%
  bind_rows()
combined_df <- combined_data %>%
  summarize(across(4:25, sum, na.rm = TRUE)) %>%
  mutate(Day = NA, Opp = NA, Half = NA)
combined_df <- combined_df %>%
  mutate(
    Rim = paste0(Rim_Make, '/', Rim_Make+Rim_Miss),
    Rim. = round((Rim_Make/(Rim_Make+Rim_Miss))*100,1),
    Paint = paste0(Paint_Make, '/', Paint_Make+Paint_Miss),
    Paint. = round((Paint_Make/(Paint_Make+Paint_Miss))*100,1),
    MidLC = paste0(MidLC_Make, '/', MidLC_Make+MidLC_Miss),
    MidLC. = round((MidLC_Make/(MidLC_Make+MidLC_Miss))*100,1),
    MidLW = paste0(MidLW_Make, '/', MidLW_Make+MidLW_Miss),
    MidLW. = round((MidLW_Make/(MidLW_Make+MidLW_Miss))*100,1),
    MidRW = paste0(MidRW_Make, '/', MidRW_Make+MidRW_Miss),
    MidRW. = round((MidRW_Make/(MidRW_Make+MidRW_Miss))*100,1),
    MidRC = paste0(MidRC_Make, '/', MidRC_Make+MidRC_Miss),
    MidRC. = round((MidRC_Make/(MidRC_Make+MidRC_Miss))*100,1),
    ThreeLC = paste0(ThreeLC_Make, '/', ThreeLC_Make+ThreeLC_Miss),
    ThreeLC. = round((ThreeLC_Make/(ThreeLC_Make+ThreeLC_Miss))*100,1),
    ThreeLW = paste0(ThreeLW_Make, '/', ThreeLW_Make+ThreeLW_Miss),
    ThreeLW. = round((ThreeLW_Make/(ThreeLW_Make+ThreeLW_Miss))*100,1),
    ThreeTop = paste0(ThreeTop_Make, '/', ThreeTop_Make+ThreeTop_Miss),
    ThreeTop. = round((ThreeTop_Make/(ThreeTop_Make+ThreeTop_Miss))*100,1),
    ThreeRW = paste0(ThreeRW_Make, '/', ThreeRW_Make+ThreeRW_Miss),
    ThreeRW. = round((ThreeRW_Make/(ThreeRW_Make+ThreeRW_Miss))*100,1),
    ThreeRC = paste0(ThreeRC_Make, '/', ThreeRC_Make+ThreeRC_Miss),
    ThreeRC. = round((ThreeRC_Make/(ThreeRC_Make+ThreeRC_Miss))*100,1),
  )
combined_df[is.na(combined_df)] = 0
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4", '#7bafd4'),
    domain = c(0, 50, 100),
    na.color = "white"
  )(values)
}
combined_df <- combined_df %>%
  mutate(
    Rim_pred = custom_color_scale(Rim.),
    Paint_pred = custom_color_scale(Paint.),
    MidLC_pred = custom_color_scale(MidLC.),
    MidLW_pred = custom_color_scale(MidLW.),
    MidRW_pred = custom_color_scale(MidRW.),
    MidRC_pred = custom_color_scale(MidRC.),
    ThreeLC_pred = custom_color_scale(ThreeLC.),
    ThreeLW_pred = custom_color_scale(ThreeLW.),
    ThreeTop_pred = custom_color_scale(ThreeTop.),
    ThreeRW_pred = custom_color_scale(ThreeRW.),
    ThreeRC_pred = custom_color_scale(ThreeRC.)
  )
full_court <- ggplot() +
  # Outline court
  geom_rect(aes(ymin = 0, ymax = -19, xmin = -8, xmax = -8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = -19, ymax = -19, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = 0, ymax = -19, xmin = 8, xmax = 8), color = 'black', fill = NA) +
  # paint color
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = combined_df$Paint_pred, color = NA, alpha = 0.5) +
  # rim color
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = combined_df$Rim_pred, color = NA, alpha = 1) +
  # mid left corner color
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidLC_pred, alpha = 0.5) +
  # mid right corner color
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidRC_pred, alpha = 0.5) +
  # mid left wing color
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  # mid right wing color
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  # three left corner color
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeLC_pred, alpha = 0.5) +
  # three right corner color
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeRC_pred, alpha = 0.5) +
  # three left wing color
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeLW_pred, alpha = 0.5) +
  # three right wing color
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeRW_pred, alpha = 0.5) +
  # three top key color
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = combined_df$ThreeTop_pred, alpha = 0.5) +
  # rim text
  geom_text(aes(x = 0, y = -5), label = combined_df$Rim, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -7), label = paste0(combined_df$Rim., "%"), size = 5, color = "black", fontface = "bold") +
  # paint text
  geom_text(aes(x = 0, y = -15), label = combined_df$Paint, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -17), label = paste0(combined_df$Paint., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left corner text
  geom_text(aes(x = -16.5, y = -5), label = combined_df$MidLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -7), label = paste0(combined_df$MidLC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right corner text
  geom_text(aes(x = 16.5, y = -5), label = combined_df$MidRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -7), label = paste0(combined_df$MidRC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left wing text
  geom_text(aes(x = -13, y = -17), label = combined_df$MidLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -19), label = paste0(combined_df$MidLW., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right wing text
  geom_text(aes(x = 13, y = -17), label = combined_df$MidRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -19), label = paste0(combined_df$MidRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three left corner text
  geom_text(aes(x = -33, y = -4), label = combined_df$ThreeLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -6), label = paste0(combined_df$ThreeLC., "%"), size = 5, color = "black", fontface = "bold") +
  # three right corner text
  geom_text(aes(x = 33, y = -4), label = combined_df$ThreeRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -6), label = paste0(combined_df$ThreeRC., "%"), size = 5, color = "black", fontface = "bold") +
  # three left wing text
  geom_text(aes(x = -23, y = -23), label = combined_df$ThreeLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -25), label = paste0(combined_df$ThreeLW., "%"), size = 5, color = "black", fontface = "bold") +
  # three right wing text
  geom_text(aes(x = 23, y = -23), label = combined_df$ThreeRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -25), label = paste0(combined_df$ThreeRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three top key text
  geom_text(aes(x = 0, y = -30), label = combined_df$ThreeTop, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -32), label = paste0(combined_df$ThreeTop., "%"), size = 5, color = "black", fontface = "bold") +
  # Backboard
  geom_segment(aes(y = -2, x = -3, yend = -2, xend = 3), color = "black") +
  # Hoop
  geom_circle(aes(y0 = -2.8, x0 = 0, r = 0.75), color = "black", fill = NA) +
  # Three-point line (arc)
  geom_arc(aes(y0 = 0, x0 = 0, r = 27, start = ((pi/2)+0.3), end = (((3*pi)/2)-0.3)), color = "black") +
  # Three-point line (sides)
  geom_segment(aes(y = 0, x = 25.76, yend = -8, xend = 25.76), color = "black") +
  geom_segment(aes(y = 0, x = -25.76, yend = -8, xend = -25.76), color = "black") +
  # Sidelines
  geom_segment(aes(y = 0, x = -30, yend = 0, xend = 30), color = "black") +
  geom_segment(aes(y = -40, x = -30, yend = -40, xend = 30), color = "black") +
  geom_segment(aes(y = 0, x = -30, yend = -40, xend = -30), color = "black") +
  geom_segment(aes(y = 0, x = 30, yend = -40, xend = 30), color = "black") +
  # Dotted rim circle
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), color = "black", fill = NA, linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  
  coord_fixed() +
  theme_void()
full_court

att_rate_df <- combined_df %>%
  mutate(
    Rim_ar = round(((Rim_Make+Rim_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    Paint_ar = round(((Paint_Make+Paint_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidLC_ar = round(((MidLC_Make+MidLC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidLW_ar = round(((MidLW_Make+MidLW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidRW_ar = round(((MidRW_Make+MidRW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    MidRC_ar = round(((MidRC_Make+MidRC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeLC_ar = round(((ThreeLC_Make+ThreeLC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeLW_ar = round(((ThreeLW_Make+ThreeLW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeTop_ar = round(((ThreeTop_Make+ThreeTop_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeRW_ar = round(((ThreeRW_Make+ThreeRW_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1),
    ThreeRC_ar = round(((ThreeRC_Make+ThreeRC_Miss)/(Rim_Make+Rim_Miss+Paint_Make+Paint_Miss+MidLC_Make+MidLC_Miss+MidLW_Make+MidLW_Miss+MidRW_Make+MidRW_Miss+MidRC_Make+MidRC_Miss+ThreeLC_Make+ThreeLC_Miss+ThreeLW_Make+ThreeLW_Miss+ThreeTop_Make+ThreeTop_Miss+ThreeRW_Make+ThreeRW_Miss+ThreeRC_Make+ThreeRC_Miss))*100,1)
  ) %>%
  select(Rim_ar, Paint_ar, MidLC_ar, MidLW_ar, MidRW_ar, MidRC_ar, ThreeLC_ar, ThreeLW_ar, ThreeTop_ar, ThreeRW_ar, ThreeRC_ar)
min_attempt_rate <- min(att_rate_df, na.rm = TRUE)
max_attempt_rate <- max(att_rate_df, na.rm = TRUE)
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4"),
    domain = c(min_attempt_rate, max_attempt_rate),
    na.color = "white"
  )(values)
}
att_rate_df <- att_rate_df %>%
  mutate(
    Rim_color = custom_color_scale(Rim_ar),
    Paint_color = custom_color_scale(Paint_ar),
    MidLC_color = custom_color_scale(MidLC_ar),
    MidLW_color = custom_color_scale(MidLW_ar),
    MidRW_color = custom_color_scale(MidRW_ar),
    MidRC_color = custom_color_scale(MidRC_ar),
    ThreeLC_color = custom_color_scale(ThreeLC_ar),
    ThreeLW_color = custom_color_scale(ThreeLW_ar),
    ThreeTop_color = custom_color_scale(ThreeTop_ar),
    ThreeRW_color = custom_color_scale(ThreeRW_ar),
    ThreeRC_color = custom_color_scale(ThreeRC_ar)
  )
full_court_ar <- ggplot() +
  # Court background color zones for each attempt rate
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = att_rate_df$Paint_color, color = NA, alpha = 0.5) +  # Paint area
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = att_rate_df$Rim_color, color = NA, alpha = 1) +  # Rim area
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = att_rate_df$MidLC_color, alpha = 0.5) +  # Mid Left Corner
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = att_rate_df$MidRC_color, alpha = 0.5) +  # Mid Right Corner
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = att_rate_df$MidLW_color, alpha = 0.5) +  # Mid Left Wing
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = att_rate_df$MidLW_color, alpha = 0.5) +
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = att_rate_df$MidRW_color, alpha = 0.5) +  # Mid Right Wing
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = att_rate_df$MidRW_color, alpha = 0.5) +
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = att_rate_df$ThreeLC_color, alpha = 0.5) +  # Three Left Corner
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = att_rate_df$ThreeRC_color, alpha = 0.5) +  # Three Right Corner
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = att_rate_df$ThreeLW_color, alpha = 0.5) +  # Three Left Wing
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = att_rate_df$ThreeRW_color, alpha = 0.5) +  # Three Right Wing
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = att_rate_df$ThreeTop_color, alpha = 0.5) +  # Three Top Key
  
  # Attempt rate text for each zone
  geom_text(aes(x = 0, y = -5), label = paste0(att_rate_df$Rim_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -15), label = paste0(att_rate_df$Paint_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -5), label = paste0(att_rate_df$MidLC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -5), label = paste0(att_rate_df$MidRC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -17), label = paste0(att_rate_df$MidLW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -17), label = paste0(att_rate_df$MidRW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -4), label = paste0(att_rate_df$ThreeLC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -4), label = paste0(att_rate_df$ThreeRC_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -23), label = paste0(att_rate_df$ThreeLW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -23), label = paste0(att_rate_df$ThreeRW_ar), size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -30), label = paste0(att_rate_df$ThreeTop_ar), size = 5, color = "black", fontface = "bold") +
  
  # Court lines and details
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_segment(aes(x = -3, y = -2, xend = 3, yend = -2), color = "black") +  # Backboard
  geom_circle(aes(x0 = 0, y0 = -2.8, r = 0.75), color = "black", fill = NA) +  # Hoop
  geom_circle(aes(x0 = 0, y0 = -4.5, r = 4.5), color = "black", linetype = "dotted") +  # Dotted rim circle
  geom_arc(aes(x0 = 0, y0 = 0, r = 27, start = pi/2 + 0.3, end = 3 * pi / 2 - 0.3), color = "black") +  # 3-point arc
  geom_segment(aes(x = 25.76, y = -8, xend = 25.76, yend = 0), color = "black") +  # Right 3-point line
  geom_segment(aes(x = -25.76, y = -8, xend = -25.76, yend = 0), color = "black") +  # Left 3-point line
  geom_segment(aes(x = -30, y = -40, xend = 30, yend = -40), color = "black") +  # Baseline
  geom_segment(aes(x = -30, y = 0, xend = 30, yend = 0), color = "black") +  # Top sideline
  geom_segment(aes(x = -30, y = 0, xend = -30, yend = -40), color = "black") +  # Left sideline
  geom_segment(aes(x = 30, y = 0, xend = 30, yend = -40), color = "black") +  # Right sideline
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  
  labs(title = "Attempt Rates", subtitle = "Per 100 FGA") +
  
  coord_fixed() +
  theme_void() + # Remove background and grid lines
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold"), plot.subtitle = element_text(size = 12, hjust = 0.5))
full_court_ar
```

```{css, echo=FALSE}
.header-tbl {
  transform: scale(0.8);
  transform-origin: top center;
}
.sd-tbl {
  transform: scale(0.8);
  transform-origin: top center;
  margin-top: -45px;
}
.first-half-tbl {
  margin-top: -20px;
  position: relative;
  z-index: 3;
}
.second-half-tbl {
  margin-top: -220px;
  position: relative;
  z-index: 3;
}
.first-court {
  transform: scale(0.55);
  transform-origin: top center;
  margin-left: -150px;
  margin-top: -10px;
  position: relative;
  z-index: 2;
}
.first-court-ar {
  transform: scale(0.55);
  transform-origin: top center;
  margin-right: -1150px;
  margin-top: -495px;
  position: relative;
  z-index: 1;
}
.second-court{
  transform: scale(0.55);
  transform-origin: top center;
  margin-left: -150px;
  margin-top: -15px;
  position: relative;
  z-index: 2;
}
.second-court-ar {
  transform: scale(0.55);
  transform-origin: top center;
  margin-right: -1150px;
  margin-top: -495px;
  position: relative;
  z-index: 1;
}
.full-tbl {
  margin-top: -220px;
  position: relative;
  z-index: 3;
}
.full-court{
  transform: scale(0.55);
  transform-origin: top center;
  margin-left: -150px;
  margin-top: -15px;
  position: relative;
  z-index: 2;
}
.full-court-ar {
  transform: scale(0.55);
  transform-origin: top center;
  margin-right: -1150px;
  margin-top: -495px;
  position: relative;
  z-index: 1;
}
```

```{r,results='asis', echo=FALSE}
cat("<div class='header-tbl'>")
print(header_tbl)
cat("</div>")
cat("<div class='sd-tbl'>")
print(sd_tbl)
cat("</div>")
cat("<div class='first-half-tbl'>")
print(first_half_tbl)
cat("</div>")
cat("<div class='first-court'>")
print(first_court)
cat("</div>")
cat("<div class='first-court-ar'>")
print(first_court_ar)
cat("</div>")
cat("<div class='second-half-tbl'>")
print(second_half_tbl)
cat("</div>")
cat("<div class='second-court'>")
print(second_court)
cat("</div>")
cat("<div class='second-court-ar'>")
print(second_court_ar)
cat("</div>")
cat("<div class='full-tbl'>")
print(full_tbl)
cat("</div>")
cat("<div class='full-court'>")
print(full_court)
cat("</div>")
cat("<div class='full-court-ar'>")
print(full_court_ar)
cat("</div>")
```

