---
title: ""
author: "Greg"
date: ""
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UNC WBB/24-25 Prac/Shiny/UNC_WBB_24-25Prac")
```

```{r, results='hide', include=FALSE, echo=FALSE}
select_week <- '02.17 - 02.23'
last_week <- '02.10 - 02.16'
```

```{r, results='hide', include=FALSE, echo=FALSE}
library(dplyr)
library(tidyr)
library(tidyverse)
library(gt)
library(gtExtras)
library(ggplot2)
library(devtools)
library(data.table)
library(cowplot)
library(gridExtra)
library(glue)
library(here)
library(magick)
library(scales)
source('https://gist.github.com/andreweatherman/0a81c7122a133a015583587573a123ff/raw/4cd6b9db1d39c46e1b93b069bc801e4eac846b19/gt_plt_bar_pct.R')
#library(cbbdata)
#cbbdata::cbd_login(username = 'glederer', password = 'Bryce.0819')
library(readxl)
library(ggforce)
```

```{r, results='hide', include=FALSE, echo=FALSE}
header_df <- data.frame(one = c('https://pbs.twimg.com/media/GbARgsbagAA7Aqk?format=jpg&name=medium'),
                        two = c(paste0('Weekly Practice Report<br>', select_week)),
                        three = c('https://upload.wikimedia.org/wikipedia/en/3/37/Jumpman_logo.svg'))
header_tbl <- header_df %>%
  gt() %>%
  text_transform(locations = cells_body(vars(one)), fn = function(x) {web_image(url = x, height = px(80))}) %>%
  text_transform(locations = cells_body(vars(three)), fn = function(x) {web_image(url = x, height = px(80))}) %>%
  cols_label(one = '', two = '', three = '') %>%
  tab_options(column_labels.hidden = TRUE) %>%
  fmt_markdown(columns = vars(two)) %>%
  tab_options(table.background.color = 'white') %>%
  tab_style(style = list(cell_text(align = "center")), locations = cells_body()) %>%
  tab_style(style = list(cell_text(weight = "bold", color = "black", size = px(28))), locations = cells_body(vars(two))) %>%
  cols_width(one ~ px(200), two ~ px(500), three ~ px(200))
header_tbl

week_data <- read.csv(paste0(select_week, ' | Practice Stats.csv'))

poss_data_edit <- week_data %>% separate(FG, into = c("FG_makes", "FG_attempts"), sep = "/")
possessions <- as.numeric(poss_data_edit$FG_attempts[15]) + as.numeric(poss_data_edit$Tov[15]) - as.numeric(poss_data_edit$Off_reb[15])
poss_df <- data.frame(one = paste0(possessions, ' Total Possessions Played'))
poss_tbl <- poss_df %>%
  gt() %>%
  cols_label(one = '') %>%
  tab_options(column_labels.hidden = TRUE) %>%
  cols_width(one ~ px(900)) %>%
  tab_style(style = list(cell_text(align = 'center', weight = 'bold', color = 'black', size = px(22), decorate = 'underline')), locations = cells_body(vars(one)))
poss_tbl

normal_tbl_df <- week_data %>%
  select(Player, Points, Ast, Reb, Off_reb, Stl, Blk, Tov, Two, Two., Three, Three.)
totals_row <- normal_tbl_df[15,]
normal_tbl_df <- normal_tbl_df[-15,]
normal_tbl_df <- normal_tbl_df %>% arrange(desc(Points), desc(Reb), desc(Ast))
normal_tbl_df <- rbind(normal_tbl_df, totals_row)
normal_tbl <- normal_tbl_df %>%
  gt() %>%
  cols_label(Player = md('**Player**'), Points = md('**PTS**'), Ast = md('**AST**'), Reb = md('**REB**'), Off_reb = md('**ORB**'), Stl = md('**STL**'), Blk = md('**BLK**'), Tov = md('**TOV**'), Two = md('**2pt**'), Two. = md('**2pt%**'), Three = md('**3pt**'), Three. = md('**3pt%**')) %>%
  gt_highlight_rows(rows = c(15), fill = 'gray95') %>%
  tab_spanner(label = md('**Box**'), columns = c(Points, Ast, Reb, Off_reb, Stl, Blk, Tov)) %>%
  tab_spanner(label = md('**Shooting**'), columns = c(Two, Two., Three, Three.)) %>%
  data_color(columns = c(Two.), palette = c("#ffffff", "#accfe8", "#7BAFD4")) %>%
  data_color(columns = c(Three.), palette = c("#ffffff", "#accfe8", "#7BAFD4")) %>%
  gt_add_divider(Player) %>%
  gt_add_divider(Tov) %>%
  cols_align(align = "center", columns = c(-Player)) %>%
  cols_align(align = "left", columns = Player)
normal_tbl
```

```{r, results='hide', include=FALSE, echo=FALSE}
path <- '/Users/gregorylederer/Desktop/UNC WBB/24-25 Prac/ShotCharts.xltm'
colnames <- c('Day', 'Week', 'Month', 'Rim_Make', 'Rim_Miss', 'Paint_Make', 'Paint_Miss', 'MidLC_Make', 'MidLC_Miss', 'MidLW_Make', 'MidLW_Miss', 'MidRW_Make', 'MidRW_Miss', 'MidRC_Make', 'MidRC_Miss', 'ThreeLC_Make', 'ThreeLC_Miss', 'ThreeLW_Make', 'ThreeLW_Miss', 'ThreeTop_Make', 'ThreeTop_Miss', 'ThreeRW_Make', 'ThreeRW_Miss', 'ThreeRC_Make', 'ThreeRC_Miss')
sheet_names <- excel_sheets(path)[-1]
shotchart_data_list <- lapply(sheet_names, function(sheet) {
  data <- read_excel(path, sheet = sheet)
  data <- data[-1, ]
  colnames(data) <- colnames
  data <- data %>%
    mutate(across(4:25, as.numeric))
  return(data)
})
names(shotchart_data_list) <- sheet_names
combined_data <- lapply(shotchart_data_list, function(data) {
  data %>%
    filter(Week == select_week)
}) %>%
  bind_rows()
combined_df <- combined_data %>%
  summarize(across(4:25, sum, na.rm = TRUE)) %>%
  mutate(Day = NA, Week = NA, Month = NA)
combined_df <- combined_df %>%
  mutate(
    Rim = paste0(Rim_Make, '/', Rim_Make+Rim_Miss),
    Rim. = round((Rim_Make/(Rim_Make+Rim_Miss))*100,1),
    Paint = paste0(Paint_Make, '/', Paint_Make+Paint_Miss),
    Paint. = round((Paint_Make/(Paint_Make+Paint_Miss))*100,1),
    MidLC = paste0(MidLC_Make, '/', MidLC_Make+MidLC_Miss),
    MidLC. = round((MidLC_Make/(MidLC_Make+MidLC_Miss))*100,1),
    MidLW = paste0(MidLW_Make, '/', MidLW_Make+MidLW_Miss),
    MidLW. = round((MidLW_Make/(MidLW_Make+MidLW_Miss))*100,1),
    MidRW = paste0(MidRW_Make, '/', MidRW_Make+MidRW_Miss),
    MidRW. = round((MidRW_Make/(MidRW_Make+MidRW_Miss))*100,1),
    MidRC = paste0(MidRC_Make, '/', MidRC_Make+MidRC_Miss),
    MidRC. = round((MidRC_Make/(MidRC_Make+MidRC_Miss))*100,1),
    ThreeLC = paste0(ThreeLC_Make, '/', ThreeLC_Make+ThreeLC_Miss),
    ThreeLC. = round((ThreeLC_Make/(ThreeLC_Make+ThreeLC_Miss))*100,1),
    ThreeLW = paste0(ThreeLW_Make, '/', ThreeLW_Make+ThreeLW_Miss),
    ThreeLW. = round((ThreeLW_Make/(ThreeLW_Make+ThreeLW_Miss))*100,1),
    ThreeTop = paste0(ThreeTop_Make, '/', ThreeTop_Make+ThreeTop_Miss),
    ThreeTop. = round((ThreeTop_Make/(ThreeTop_Make+ThreeTop_Miss))*100,1),
    ThreeRW = paste0(ThreeRW_Make, '/', ThreeRW_Make+ThreeRW_Miss),
    ThreeRW. = round((ThreeRW_Make/(ThreeRW_Make+ThreeRW_Miss))*100,1),
    ThreeRC = paste0(ThreeRC_Make, '/', ThreeRC_Make+ThreeRC_Miss),
    ThreeRC. = round((ThreeRC_Make/(ThreeRC_Make+ThreeRC_Miss))*100,1),
  )
combined_df[is.na(combined_df)] = 0
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4", '#7bafd4'),
    domain = c(0, 50, 100),
    na.color = "white"
  )(values)
}
combined_df <- combined_df %>%
  mutate(
    Rim_pred = custom_color_scale(Rim.),
    Paint_pred = custom_color_scale(Paint.),
    MidLC_pred = custom_color_scale(MidLC.),
    MidLW_pred = custom_color_scale(MidLW.),
    MidRW_pred = custom_color_scale(MidRW.),
    MidRC_pred = custom_color_scale(MidRC.),
    ThreeLC_pred = custom_color_scale(ThreeLC.),
    ThreeLW_pred = custom_color_scale(ThreeLW.),
    ThreeTop_pred = custom_color_scale(ThreeTop.),
    ThreeRW_pred = custom_color_scale(ThreeRW.),
    ThreeRC_pred = custom_color_scale(ThreeRC.)
  )
court_thisweek <- ggplot() +
  # Outline court
  geom_rect(aes(ymin = 0, ymax = -19, xmin = -8, xmax = -8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = -19, ymax = -19, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = 0, ymax = -19, xmin = 8, xmax = 8), color = 'black', fill = NA) +
  # paint color
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = combined_df$Paint_pred, color = NA, alpha = 0.5) +
  # rim color
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = combined_df$Rim_pred, color = NA, alpha = 1) +
  # mid left corner color
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidLC_pred, alpha = 0.5) +
  # mid right corner color
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidRC_pred, alpha = 0.5) +
  # mid left wing color
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  # mid right wing color
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  # three left corner color
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeLC_pred, alpha = 0.5) +
  # three right corner color
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeRC_pred, alpha = 0.5) +
  # three left wing color
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeLW_pred, alpha = 0.5) +
  # three right wing color
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeRW_pred, alpha = 0.5) +
  # three top key color
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = combined_df$ThreeTop_pred, alpha = 0.5) +
  # rim text
  geom_text(aes(x = 0, y = -5), label = combined_df$Rim, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -7), label = paste0(combined_df$Rim., "%"), size = 5, color = "black", fontface = "bold") +
  # paint text
  geom_text(aes(x = 0, y = -15), label = combined_df$Paint, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -17), label = paste0(combined_df$Paint., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left corner text
  geom_text(aes(x = -16.5, y = -5), label = combined_df$MidLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -7), label = paste0(combined_df$MidLC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right corner text
  geom_text(aes(x = 16.5, y = -5), label = combined_df$MidRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -7), label = paste0(combined_df$MidRC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left wing text
  geom_text(aes(x = -13, y = -17), label = combined_df$MidLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -19), label = paste0(combined_df$MidLW., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right wing text
  geom_text(aes(x = 13, y = -17), label = combined_df$MidRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -19), label = paste0(combined_df$MidRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three left corner text
  geom_text(aes(x = -33, y = -4), label = combined_df$ThreeLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -6), label = paste0(combined_df$ThreeLC., "%"), size = 5, color = "black", fontface = "bold") +
  # three right corner text
  geom_text(aes(x = 33, y = -4), label = combined_df$ThreeRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -6), label = paste0(combined_df$ThreeRC., "%"), size = 5, color = "black", fontface = "bold") +
  # three left wing text
  geom_text(aes(x = -23, y = -23), label = combined_df$ThreeLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -25), label = paste0(combined_df$ThreeLW., "%"), size = 5, color = "black", fontface = "bold") +
  # three right wing text
  geom_text(aes(x = 23, y = -23), label = combined_df$ThreeRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -25), label = paste0(combined_df$ThreeRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three top key text
  geom_text(aes(x = 0, y = -30), label = combined_df$ThreeTop, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -32), label = paste0(combined_df$ThreeTop., "%"), size = 5, color = "black", fontface = "bold") +
  # Backboard
  geom_segment(aes(y = -2, x = -3, yend = -2, xend = 3), color = "black") +
  # Hoop
  geom_circle(aes(y0 = -2.8, x0 = 0, r = 0.75), color = "black", fill = NA) +
  # Three-point line (arc)
  geom_arc(aes(y0 = 0, x0 = 0, r = 27, start = ((pi/2)+0.3), end = (((3*pi)/2)-0.3)), color = "black") +
  # Three-point line (sides)
  geom_segment(aes(y = 0, x = 25.76, yend = -8, xend = 25.76), color = "black") +
  geom_segment(aes(y = 0, x = -25.76, yend = -8, xend = -25.76), color = "black") +
  # Sidelines
  geom_segment(aes(y = 0, x = -30, yend = 0, xend = 30), color = "black") +
  geom_segment(aes(y = -40, x = -30, yend = -40, xend = 30), color = "black") +
  geom_segment(aes(y = 0, x = -30, yend = -40, xend = -30), color = "black") +
  geom_segment(aes(y = 0, x = 30, yend = -40, xend = 30), color = "black") +
  # Dotted rim circle
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), color = "black", fill = NA, linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  
  coord_fixed() +
  theme_void() +
  labs(
    title = 'This Week',
    subtitle = select_week
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
    plot.subtitle = element_text(hjust = 0.5, size = 12, face = "italic", color = "black")
  )
court_thisweek
```

```{r, results='hide', include=FALSE, echo=FALSE}
path <- '/Users/gregorylederer/Desktop/UNC WBB/24-25 Prac/ShotCharts.xltm'
colnames <- c('Day', 'Week', 'Month', 'Rim_Make', 'Rim_Miss', 'Paint_Make', 'Paint_Miss', 'MidLC_Make', 'MidLC_Miss', 'MidLW_Make', 'MidLW_Miss', 'MidRW_Make', 'MidRW_Miss', 'MidRC_Make', 'MidRC_Miss', 'ThreeLC_Make', 'ThreeLC_Miss', 'ThreeLW_Make', 'ThreeLW_Miss', 'ThreeTop_Make', 'ThreeTop_Miss', 'ThreeRW_Make', 'ThreeRW_Miss', 'ThreeRC_Make', 'ThreeRC_Miss')
sheet_names <- excel_sheets(path)
shotchart_data_list <- lapply(sheet_names, function(sheet) {
  data <- read_excel(path, sheet = sheet)
  data <- data[-1, ]
  colnames(data) <- colnames
  data <- data %>%
    mutate(across(4:25, as.numeric))
  return(data)
})
names(shotchart_data_list) <- sheet_names
combined_data <- lapply(shotchart_data_list, function(data) {
  data %>%
    filter(Week == last_week)
}) %>%
  bind_rows()
combined_df <- combined_data %>%
  summarize(across(4:25, sum, na.rm = TRUE)) %>%
  mutate(Day = NA, Week = NA, Month = NA)
combined_df <- combined_df %>%
  mutate(
    Rim = paste0(Rim_Make, '/', Rim_Make+Rim_Miss),
    Rim. = round((Rim_Make/(Rim_Make+Rim_Miss))*100,1),
    Paint = paste0(Paint_Make, '/', Paint_Make+Paint_Miss),
    Paint. = round((Paint_Make/(Paint_Make+Paint_Miss))*100,1),
    MidLC = paste0(MidLC_Make, '/', MidLC_Make+MidLC_Miss),
    MidLC. = round((MidLC_Make/(MidLC_Make+MidLC_Miss))*100,1),
    MidLW = paste0(MidLW_Make, '/', MidLW_Make+MidLW_Miss),
    MidLW. = round((MidLW_Make/(MidLW_Make+MidLW_Miss))*100,1),
    MidRW = paste0(MidRW_Make, '/', MidRW_Make+MidRW_Miss),
    MidRW. = round((MidRW_Make/(MidRW_Make+MidRW_Miss))*100,1),
    MidRC = paste0(MidRC_Make, '/', MidRC_Make+MidRC_Miss),
    MidRC. = round((MidRC_Make/(MidRC_Make+MidRC_Miss))*100,1),
    ThreeLC = paste0(ThreeLC_Make, '/', ThreeLC_Make+ThreeLC_Miss),
    ThreeLC. = round((ThreeLC_Make/(ThreeLC_Make+ThreeLC_Miss))*100,1),
    ThreeLW = paste0(ThreeLW_Make, '/', ThreeLW_Make+ThreeLW_Miss),
    ThreeLW. = round((ThreeLW_Make/(ThreeLW_Make+ThreeLW_Miss))*100,1),
    ThreeTop = paste0(ThreeTop_Make, '/', ThreeTop_Make+ThreeTop_Miss),
    ThreeTop. = round((ThreeTop_Make/(ThreeTop_Make+ThreeTop_Miss))*100,1),
    ThreeRW = paste0(ThreeRW_Make, '/', ThreeRW_Make+ThreeRW_Miss),
    ThreeRW. = round((ThreeRW_Make/(ThreeRW_Make+ThreeRW_Miss))*100,1),
    ThreeRC = paste0(ThreeRC_Make, '/', ThreeRC_Make+ThreeRC_Miss),
    ThreeRC. = round((ThreeRC_Make/(ThreeRC_Make+ThreeRC_Miss))*100,1),
  )
combined_df[is.na(combined_df)] = 0
custom_color_scale <- function(values) {
  col_numeric(
    palette = c("white", "#7bafd4", '#7bafd4'),
    domain = c(0, 50, 100),
    na.color = "white"
  )(values)
}
combined_df <- combined_df %>%
  mutate(
    Rim_pred = custom_color_scale(Rim.),
    Paint_pred = custom_color_scale(Paint.),
    MidLC_pred = custom_color_scale(MidLC.),
    MidLW_pred = custom_color_scale(MidLW.),
    MidRW_pred = custom_color_scale(MidRW.),
    MidRC_pred = custom_color_scale(MidRC.),
    ThreeLC_pred = custom_color_scale(ThreeLC.),
    ThreeLW_pred = custom_color_scale(ThreeLW.),
    ThreeTop_pred = custom_color_scale(ThreeTop.),
    ThreeRW_pred = custom_color_scale(ThreeRW.),
    ThreeRC_pred = custom_color_scale(ThreeRC.)
  )
court_lastweek <- ggplot() +
  # Outline court
  geom_rect(aes(ymin = 0, ymax = -19, xmin = -8, xmax = -8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = -19, ymax = -19, xmin = -8, xmax = 8), color = 'black', fill = NA) +
  geom_rect(aes(ymin = 0, ymax = -19, xmin = 8, xmax = 8), color = 'black', fill = NA) +
  # paint color
  geom_rect(aes(ymin = -19, ymax = 0, xmin = -8, xmax = 8), fill = combined_df$Paint_pred, color = NA, alpha = 0.5) +
  # rim color
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), fill = combined_df$Rim_pred, color = NA, alpha = 1) +
  # mid left corner color
  geom_polygon(aes(x = c(-24.7, -8, -8, -25.76, -25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidLC_pred, alpha = 0.5) +
  # mid right corner color
  geom_polygon(aes(x = c(24.7, 8, 8, 25.76, 25.76),
                   y = c(-11, -11, 0, 0, -8)), fill = combined_df$MidRC_pred, alpha = 0.5) +
  # mid left wing color
  geom_polygon(aes(x = c(-8, 0, 0, -4, -8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(-24.7, -8, -8, -10, -11, -12, -13, -13.5, -14, -14.5, -15, -16, -16.5, -17, -18, -19, -20, -21, -22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidLW_pred, alpha = 0.5) +
  # mid right wing color
  geom_polygon(aes(x = c(8, 0, 0, 4, 8),
                   y = c(-19, -19, -27, -26.8, -25.8)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  geom_polygon(aes(x = c(24.7, 8, 8, 10, 11, 12, 13, 13.5, 14, 14.5, 15, 16, 16.5, 17, 18, 19, 20, 21, 22),
                   y = c(-11, -11, -25.8, -25, -24.7, -24, -23.8, -23.4, -23, -22.8, -22.2, -21.8, -21.5, -21, -20.2, -19.3, -18.3, -17.2, -16)), fill = combined_df$MidRW_pred, alpha = 0.5) +
  # three left corner color
  geom_polygon(aes(x = c(-30, -25.8, -25.8, -24.5, -30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeLC_pred, alpha = 0.5) +
  # three right corner color
  geom_polygon(aes(x = c(30, 25.8, 25.8, 24.5, 30),
                   y = c(0, 0, -8, -11, -11)), fill = combined_df$ThreeRC_pred, alpha = 0.5) +
  # three left wing color
  geom_polygon(aes(x = c(-30, -30, -24.5, -23, -22, -21, -20, -19, -13, -13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeLW_pred, alpha = 0.5) +
  # three right wing color
  geom_polygon(aes(x = c(30, 30, 24.5, 23, 22, 21, 20, 19, 13, 13),
                   y = c(-40, -11, -11, -14, -15.5, -17.2, -18.3, -19.3, -23.8, -40)), fill = combined_df$ThreeRW_pred, alpha = 0.5) +
  # three top key color
  geom_polygon(aes(x = c(13, -13, -13, -10, -8, -5, -3, 0, 3, 5, 8, 10, 13),
                   y = c(-40, -40, -23.8, -25, -25.8, -26.3, -26.7, -27, -26.7, -26.3, -25.8, -25, -23.8)), fill = combined_df$ThreeTop_pred, alpha = 0.5) +
  # rim text
  geom_text(aes(x = 0, y = -5), label = combined_df$Rim, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -7), label = paste0(combined_df$Rim., "%"), size = 5, color = "black", fontface = "bold") +
  # paint text
  geom_text(aes(x = 0, y = -15), label = combined_df$Paint, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -17), label = paste0(combined_df$Paint., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left corner text
  geom_text(aes(x = -16.5, y = -5), label = combined_df$MidLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -16.5, y = -7), label = paste0(combined_df$MidLC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right corner text
  geom_text(aes(x = 16.5, y = -5), label = combined_df$MidRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 16.5, y = -7), label = paste0(combined_df$MidRC., "%"), size = 5, color = "black", fontface = "bold") +
  # mid left wing text
  geom_text(aes(x = -13, y = -17), label = combined_df$MidLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -13, y = -19), label = paste0(combined_df$MidLW., "%"), size = 5, color = "black", fontface = "bold") +
  # mid right wing text
  geom_text(aes(x = 13, y = -17), label = combined_df$MidRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 13, y = -19), label = paste0(combined_df$MidRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three left corner text
  geom_text(aes(x = -33, y = -4), label = combined_df$ThreeLC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -33, y = -6), label = paste0(combined_df$ThreeLC., "%"), size = 5, color = "black", fontface = "bold") +
  # three right corner text
  geom_text(aes(x = 33, y = -4), label = combined_df$ThreeRC, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 33, y = -6), label = paste0(combined_df$ThreeRC., "%"), size = 5, color = "black", fontface = "bold") +
  # three left wing text
  geom_text(aes(x = -23, y = -23), label = combined_df$ThreeLW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = -23, y = -25), label = paste0(combined_df$ThreeLW., "%"), size = 5, color = "black", fontface = "bold") +
  # three right wing text
  geom_text(aes(x = 23, y = -23), label = combined_df$ThreeRW, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 23, y = -25), label = paste0(combined_df$ThreeRW., "%"), size = 5, color = "black", fontface = "bold") +
  # three top key text
  geom_text(aes(x = 0, y = -30), label = combined_df$ThreeTop, size = 5, color = "black", fontface = "bold") +
  geom_text(aes(x = 0, y = -32), label = paste0(combined_df$ThreeTop., "%"), size = 5, color = "black", fontface = "bold") +
  # Backboard
  geom_segment(aes(y = -2, x = -3, yend = -2, xend = 3), color = "black") +
  # Hoop
  geom_circle(aes(y0 = -2.8, x0 = 0, r = 0.75), color = "black", fill = NA) +
  # Three-point line (arc)
  geom_arc(aes(y0 = 0, x0 = 0, r = 27, start = ((pi/2)+0.3), end = (((3*pi)/2)-0.3)), color = "black") +
  # Three-point line (sides)
  geom_segment(aes(y = 0, x = 25.76, yend = -8, xend = 25.76), color = "black") +
  geom_segment(aes(y = 0, x = -25.76, yend = -8, xend = -25.76), color = "black") +
  # Sidelines
  geom_segment(aes(y = 0, x = -30, yend = 0, xend = 30), color = "black") +
  geom_segment(aes(y = -40, x = -30, yend = -40, xend = 30), color = "black") +
  geom_segment(aes(y = 0, x = -30, yend = -40, xend = -30), color = "black") +
  geom_segment(aes(y = 0, x = 30, yend = -40, xend = 30), color = "black") +
  # Dotted rim circle
  geom_circle(aes(y0 = -4.5, x0 = 0, r = 4.5), color = "black", fill = NA, linetype = 'dotted') +
  # Left baseline & corner 3 line
  geom_segment(aes(y = -11, x = -30, yend = -11, xend = -8), color = "black", linetype = 'dotted') +
  # Right baseline & corner 3 line
  geom_segment(aes(y = -11, x = 8, yend = -11, xend = 30), color = "black", linetype = 'dotted') +
  # FT line to top key three
  geom_segment(aes(y = -19, x = 0, yend = -27, xend = 0), color = "black", linetype = 'dotted') +
  # Left wing three
  geom_segment(aes(y = -24, x = -13, yend = -40, xend = -13), color = "black", linetype = 'dotted') +
  # Right wing three
  geom_segment(aes(y = -24, x = 13, yend = -40, xend = 13), color = "black", linetype = 'dotted') +
  
  coord_fixed() +
  theme_void() +
  labs(
    title = 'Last Week',
    subtitle = last_week
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
    plot.subtitle = element_text(hjust = 0.5, size = 12, face = "italic", color = "black")
  )
court_lastweek
```

```{r, results='hide', include=FALSE, echo=FALSE}
last_week_data <- read.csv(paste0(last_week, ' | Practice Stats.csv'))
week_data_total <- week_data[15,]
week_data_total <- week_data_total %>% separate(FG, into = c("FG_makes", "FG_misses"), sep = "/")
week_data_total <- week_data_total %>%
  mutate(
    Ast_FGM = round((as.numeric(Ast)/as.numeric(FG_makes))*100,1),
    ORTG = round((as.numeric(Points)/possessions)*100,1),
    Tov. = round((as.numeric(Tov)/possessions)*100,1)
  )
last_week_data_total <- last_week_data[15,]
last_week_data_total <- last_week_data_total %>% separate(FG, into = c("FG_makes", "FG_misses"), sep = "/")
last_week_data_total <- last_week_data_total %>%
  mutate(
    Ast_FGM = round((as.numeric(Ast)/as.numeric(FG_makes))*100,1),
    ORTG = round((as.numeric(Points)/possessions)*100,1),
    Tov. = round((as.numeric(Tov)/possessions)*100,1)
  )

improvement_df <- data.frame(Stat = c('3pt Att. Rate', 'Ast/Tov', 'Ast/FGM', 'ORTG', 'Tov%', 'eFG%', 'FG%'),
                             ThisWeek = c(week_data_total$Three_att, week_data_total$Ast_Tov, week_data_total$Ast_FGM, week_data_total$ORTG, week_data_total$Tov., week_data_total$eFG., week_data_total$FG.),
                             LastWeek = c(last_week_data_total$Three_att, last_week_data_total$Ast_Tov, last_week_data_total$Ast_FGM, last_week_data_total$ORTG, last_week_data_total$Tov., last_week_data_total$eFG., last_week_data_total$FG.))
improvement_df <- improvement_df %>% mutate(across(2:3, as.numeric))
improvement_df$Difference <- improvement_df$ThisWeek - improvement_df$LastWeek
improvement_df <- improvement_df %>%
  arrange(desc(abs(Difference)))
improvement_df$Difference[improvement_df$Stat == 'Tov%'] <- improvement_df$Difference[improvement_df$Stat == 'Tov%'] * -1
improvement_tbl <- improvement_df %>%
  gt() %>%
  cols_label(Stat = md('**Stat**'), ThisWeek = md('**This Week**'), LastWeek = md('**Last Week**'), Difference = md('**Difference**')) %>%
  gt_add_divider(Stat, weight = px(1.5)) %>%
  gt_add_divider(LastWeek, weight = px(1.5)) %>%
  tab_style(style = cell_text(align = "center", weight = "bold", decorate = 'underline'), locations = cells_column_labels(everything())) %>%
  cols_align(align = "center", columns = c(ThisWeek, LastWeek, Difference)) %>%
  tab_style(style = cell_text(weight = "bold", align = "left"), locations = cells_body(columns = Stat)) %>%
  data_color(columns = c(Difference), colors = col_numeric(palette = c("firebrick", "white", "green4"), domain = c(min(improvement_df$Difference), 0, max(improvement_df$Difference)))) %>%
  cols_width(ThisWeek ~ px(70), LastWeek ~ px(70), Stat ~ px(80), Difference ~ px(100))
improvement_tbl
```

```{r, results='hide', include=FALSE, echo=FALSE}
NCAA_stats <- read.csv('/Users/gregorylederer/Desktop/UNC WBB/23-24 WBB Stats.csv')
NCAA_stats <- NCAA_stats %>%
  mutate(
    Team = School,
    ORTG = TM_ORTG,
    eFG. = round(TM_eFG.*100,1),
    FG. = round(TM_FG.*100,1),
    Three_att = round(TM_3PAr*100,1),
    Tov. = TM_TOV.,
    Ast_Tov = round((TM_AST/TM_TOV)*100,1),
    Ast_FGM = round((TM_AST/TM_FG)*100,1)
  ) %>%
  select(Team, ORTG, eFG., FG., Three_att, Tov., Ast_Tov, Ast_FGM)
new_row <- tibble(
  Team = 'Practice',
  ORTG = week_data_total$ORTG,
  eFG. = week_data_total$eFG.,
  FG. = week_data_total$FG.,
  Three_att = week_data_total$Three_att,
  Tov. = week_data_total$Tov.,
  Ast_Tov = week_data_total$Ast_Tov,
  Ast_FGM = week_data_total$Ast_FGM
)
NCAA_stats <- NCAA_stats %>% add_row(new_row)
NCAA_stats <- NCAA_stats %>%
  mutate(across(c(ORTG, eFG., FG., Three_att, Tov., Ast_Tov, Ast_FGM), percent_rank, .names = '{col}_ptile'))
prac_row <- NCAA_stats %>% filter(Team == 'Practice')
bars_df <- data.frame(Stat = c('3pt Att. Rate', 'Ast/Tov', 'Ast/FGM', 'ORTG', 'Tov%', 'eFG%', 'FG%'),
                      ptile = c(prac_row$Three_att_ptile, prac_row$Ast_Tov_ptile, prac_row$Ast_FGM_ptile, prac_row$ORTG_ptile, prac_row$Tov._ptile, prac_row$eFG._ptile, prac_row$FG._ptile))
bars_df <- bars_df[match(improvement_df$Stat, bars_df$Stat), ]
bars_tbl <- bars_df %>%
  gt() %>%
  cols_label(Stat = md('**Stat**'), ptile = md('**%tile Comp. to NCAA Avg.**')) %>%
  gt_bars(ptile, labels = TRUE, fill = '#7bafd4', domain = 0:1, digits = 0) %>%
  gt_add_divider(Stat, weight = px(1)) %>%
  tab_style(style = cell_text(align = "center", weight = "bold"), locations = cells_column_labels(everything())) %>%
  tab_style(style = cell_text(weight = "bold", align = "left"), locations = cells_body(columns = Stat)) %>%
  cols_align(align = "center", columns = ptile) %>%
  cols_width(Stat ~ px(80), ptile ~ px(240))
bars_tbl
```

```{css, echo=FALSE}
.header-tbl {
  transform: scale(0.8);
  transform-origin: top center;
}
.poss-tbl {
  transform: scale(0.8);
  transform-origin: top center;
  margin-top: -41px;
}
.prac-tbl {
  transform: scale(0.7);
  transform-origin: top center;
  margin-top: -29px;
  margin-left: -231px;
  position: relative;
  z-index: 3;
}
.improve-tbl {
  transform: scale(0.7);
  transform-origin: top center;
  margin-top: -624px;
  margin-right: -470px;
}
.bars-tbl {
  transform: scale(0.7);
  transform-origin: top center;
  margin-top: -105px;
  margin-right: -470px;
  z-index: 3;
  position: relative;
}
.court-this-week {
  transform: scale(0.6);
  transform-origin: top center;
  margin-top: -120px;
  margin-left: -90px;
  z-index: 2;
  position: relative;
}
.court-last-week {
  transform: scale(0.46);
  transform-origin: top center;
  margin-top: -415px;
  margin-right: -1000px;
  z-index: 1;
  position: relative;
}
```

```{r,results='asis', echo=FALSE}
cat("<div class='header-tbl'>")
print(header_tbl)
cat("</div>")
cat("<div class='poss-tbl'>")
print(poss_tbl)
cat("</div>")
cat("<div class='prac-tbl'>")
print(normal_tbl)
cat("</div>")
cat("<div class='improve-tbl'>")
print(improvement_tbl)
cat("</div>")
cat("<div class='bars-tbl'>")
print(bars_tbl)
cat("</div>")
cat("<div class='court-this-week'>")
print(court_thisweek)
cat("</div>")
cat("<div class='court-last-week'>")
print(court_lastweek)
cat("</div>")
```

